name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Wally install
        run: |
          wally install
      - name: Build place file
        run: |
          rojo build default.project.json -o  PropertySystem.rbxl
      - name: Get version
        id: get_version
        # run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Changelog
        run: python3 last_changelog.py CHANGELOG.md > log.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: log.md
          fail_on_unmatched_files: true
          files: |
            PropertySystem.rbxl
